import logging
from typing import Annotated

from fastapi import APIRouter, BackgroundTasks, Path, status, WebSocket, WebSocketDisconnect

from app.core.config.settings import settings
from app.core.exceptions import AppHTTPException
from app.core.dependencies import ReadSessionDep, SessionDep, SkipQuery, LimitQuery
from ..crud import alerts_crud
from ..schemas.alerts_schemas import AlertSchema, AlertCreateSchema, AlertUpdateSchema, AlertBulkActionResponse, UnreadCountResponse
from ..utils.alerts_websocket import manager

router = APIRouter(prefix="/api/alerts", tags=["Alerts"])
ws_router = APIRouter()

logger = logging.getLogger(__name__)

AlertId = Annotated[int, Path(ge=1, description="Alert ID")]
ModuleName = Annotated[str, Path(min_length=1, max_length=100, description="Module name")]


@ws_router.websocket("/ws/alerts")
async def websocket_endpoint(websocket: WebSocket, token: str = ""):
    """WebSocket endpoint for real-time alert notifications.

    When API_WS_SECRET_TOKEN is set, the token query parameter must match.
    Leave the setting empty to allow all connections (development default).
    """
    configured_token = settings.api.ws_secret_token
    if configured_token and token != configured_token:
        await websocket.close(code=4001)
        logger.warning("WebSocket connection rejected: invalid token from %s", websocket.client)
        return

    await manager.connect(websocket)
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        pass
    except Exception as e:
        logger.warning("WebSocket connection closed unexpectedly: %s", e)
    finally:
        manager.disconnect(websocket)


# Fixed paths must be defined before parameterized paths to avoid conflicts

@router.get(
    "/count/unread",
    response_model=UnreadCountResponse,
    summary="Get unread alert count",
    description="Returns the number of alerts that have not been marked as read",
)
async def get_unread_count(db: ReadSessionDep) -> UnreadCountResponse:
    """Get count of unread alerts"""
    count = await alerts_crud.count_unread_alerts(db)
    return UnreadCountResponse(unread_count=count)


@router.get(
    "/module/{module}",
    response_model=list[AlertSchema],
    response_model_exclude_none=True,
    summary="Get alerts by module",
    description="Retrieve all alerts generated by a specific module, with pagination",
)
async def get_alerts_for_module(
    module: ModuleName,
    db: ReadSessionDep,
    skip: SkipQuery = 0,
    limit: LimitQuery = 100,
) -> list[AlertSchema]:
    """Get all alerts for a specific module with pagination"""
    return await alerts_crud.get_alerts_by_module(db, module, skip=skip, limit=limit)


@router.get(
    "",
    response_model=list[AlertSchema],
    response_model_exclude_none=True,
    summary="List alerts",
    description="Retrieve all alerts with pagination support",
)
async def read_alerts(
    db: ReadSessionDep,
    skip: SkipQuery = 0,
    limit: LimitQuery = 100,
) -> list[AlertSchema]:
    """Retrieve all alerts with pagination"""
    return await alerts_crud.get_all_alerts(db, skip=skip, limit=limit)


@router.post(
    "",
    response_model=AlertSchema,
    response_model_exclude_none=True,
    status_code=status.HTTP_201_CREATED,
    summary="Create alert",
    description="Create a new alert and broadcast it to all connected WebSocket clients",
)
async def create_new_alert(
    background_tasks: BackgroundTasks,
    alert: AlertCreateSchema,
    db: SessionDep,
) -> AlertSchema:
    """Create a new alert and broadcast it via WebSocket"""
    new_alert = await alerts_crud.create_alert(db, module=alert.module, title=alert.title, message=alert.message)
    logger.info("Created alert %s for module %s", new_alert.id, new_alert.module)

    background_tasks.add_task(
        manager.broadcast,
        AlertSchema.model_validate(new_alert).model_dump(mode="json"),
    )

    return new_alert


@router.patch(
    "",
    response_model=AlertBulkActionResponse,
    summary="Mark all alerts as read",
    description="Mark every unread alert as read in a single bulk operation",
)
async def mark_all_alerts_read(db: SessionDep) -> AlertBulkActionResponse:
    """Mark all alerts as read"""
    count = await alerts_crud.bulk_mark_all_alerts_read(db)
    logger.info("Marked %s alerts as read", count)
    return AlertBulkActionResponse(message="All alerts marked as read", count=count)


@router.delete(
    "",
    response_model=AlertBulkActionResponse,
    summary="Delete all alerts",
    description="Permanently delete all alerts",
)
async def delete_all_alerts_endpoint(db: SessionDep) -> AlertBulkActionResponse:
    """Delete all alerts"""
    count = await alerts_crud.bulk_delete_all_alerts(db)
    logger.warning("Bulk delete executed: %d alerts permanently removed", count)
    return AlertBulkActionResponse(message="All alerts deleted", count=count)


@router.get(
    "/{alert_id}",
    response_model=AlertSchema,
    response_model_exclude_none=True,
    summary="Get alert",
    description="Retrieve a specific alert by its ID",
    responses={404: {"description": "Alert not found"}},
)
async def get_alert(alert_id: AlertId, db: ReadSessionDep) -> AlertSchema:
    """Get a specific alert by ID"""
    alert = await alerts_crud.get_alert_by_id(db, alert_id)
    if not alert:
        raise AppHTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Alert not found",
            error_code="ALERT_NOT_FOUND",
        )
    return alert


@router.patch(
    "/{alert_id}",
    response_model=AlertSchema,
    response_model_exclude_none=True,
    summary="Update alert",
    description="Partially update an alert, for example to mark it as read or unread",
    responses={404: {"description": "Alert not found"}},
)
async def update_alert(alert_id: AlertId, update_data: AlertUpdateSchema, db: SessionDep) -> AlertSchema:
    """Partially update an alert (e.g. mark as read or unread)"""
    alert = await alerts_crud.update_alert_read_status(db, alert_id, update_data.read)
    if not alert:
        raise AppHTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Alert not found",
            error_code="ALERT_NOT_FOUND",
        )
    logger.info("Set alert %s read status to %s", alert_id, update_data.read)
    return alert


@router.delete(
    "/{alert_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete alert",
    description="Permanently delete a specific alert by its ID",
    responses={404: {"description": "Alert not found"}},
)
async def delete_single_alert(alert_id: AlertId, db: SessionDep) -> None:
    """Delete a specific alert"""
    alert = await alerts_crud.delete_alert_by_id(db, alert_id)
    if not alert:
        raise AppHTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Alert not found",
            error_code="ALERT_NOT_FOUND",
        )
    logger.info("Deleted alert %s", alert_id)
